<?xml version="1.0"?>
<package format="3">
  <name>xfly_bridge</name>
  <version>0.1.0</version>
  <description>Bluetooth Low Energy communication bridge and teleoperation for the XFly ornithopter</description>
  <maintainer email="toumieh@epfl.ch">Charbel Toumieh</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <exec_depend>python3-bleak</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
